export const enum MchgStage {
  PAUSED = 'PAUSED',
  CHOOSING_QUESTION = 'CHOOSING_QUESTION',
  ANSWERING_MAIN_QUESTION = 'ANSWERING_MAIN_QUESTION', // Chướng ngại vật
  ANSWERING_SUB_QUESTION = 'ANSWERING_SUB_QUESTION', // Câu hỏi phụ
  UPDATE_RESULTS = 'UPDATE_RESULTS',
}
